language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '11'
  - '10'
  - '8'
script:
  - npm run test:prod && npm run build
jobs:
  include:
    - stage: aaaaa
      node_js: "8"
      script:
        - echo "aaaaaa-bbbbbbbbbb-cccccccc"
        - echo "aaaaaa-bbbbbbbbbb-cccccccc"
        - echo "aaaaaa-bbbbbbbbbb-cccccccc"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
