language: node_js
os:
  - linux
notifications:
  email: false
node_js:
  - '10'
script:
  - npm run prepub
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run semantic-release; fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
    - next
    - gh-pages
